### ISSUE TITLE
Bang??

### ISSUE THREAD

**Issue by Zilfs** [TimotiusMM/WebsiteNativeHotel#1]
ini apaan bang, aku mah masi pemula 😓😓

**Comment by TimotiusMM** [comment]
ngomong ama gigi nya bagus sono

**Comment by Zilfs** [comment]
![IMG_4961](https://github.com/TimotiusMM/WebsiteNativeHotel/assets/117014577/d0b63e54-2841-4c24-9020-67dc35cac3e9)
